import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export async function generateGameSummaryPDF(
  analysis: any,
  gameStats: any
): Promise<Blob> {
  // Create a temporary container with the summary content
  const container = document.createElement('div')
  container.style.width = '1000px'
  container.style.padding = '40px'
  container.style.backgroundColor = 'white'
  container.style.fontFamily = 'Arial, sans-serif'
  container.innerHTML = `
    <div style="text-align: center; margin-bottom: 30px;">
      <h1 style="color: #6366f1; margin: 0; font-size: 28px;">INVESIM - Game Summary Report</h1>
      <p style="color: #666; margin: 10px 0 0 0; font-size: 14px;">Investment Simulation Analysis</p>
    </div>

    <div style="margin-bottom: 25px; padding: 20px; background-color: #f5f5f5; border-radius: 8px;">
      <h2 style="color: #333; margin-top: 0; font-size: 18px;">Game Results</h2>
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; font-size: 14px;">
        <div>
          <p style="margin: 5px 0;"><strong>Your Score:</strong> ₹${gameStats.playerScore.toLocaleString('en-IN')}</p>
          <p style="margin: 5px 0;"><strong>AI Score:</strong> ₹${gameStats.aiScore.toLocaleString('en-IN')}</p>
          <p style="margin: 5px 0;"><strong>Result:</strong> <span style="color: ${gameStats.result === 'win' ? '#10b981' : '#ef4444'}; font-weight: bold;">${gameStats.result.toUpperCase()}</span></p>
        </div>
        <div>
          <p style="margin: 5px 0;"><strong>Difficulty:</strong> ${gameStats.difficulty}</p>
          <p style="margin: 5px 0;"><strong>Duration:</strong> ${gameStats.yearsPlayed} years</p>
          <p style="margin: 5px 0;"><strong>Total Invested:</strong> ₹${gameStats.totalInvested.toLocaleString('en-IN')}</p>
        </div>
      </div>
    </div>

    <div style="margin-bottom: 25px; padding: 20px; background-color: #f9fafb; border-left: 4px solid #6366f1;">
      <h2 style="color: #333; margin-top: 0; font-size: 18px;">Overall Summary</h2>
      <p style="color: #555; line-height: 1.6; font-size: 14px;">${analysis.summary}</p>
    </div>

    <div style="margin-bottom: 25px;">
      <h2 style="color: #333; margin-top: 0; font-size: 18px;">✅ Strengths</h2>
      <ul style="color: #555; font-size: 14px; line-height: 1.8;">
        ${analysis.strengths.map((s: string) => `<li>${s}</li>`).join('')}
      </ul>
    </div>

    <div style="margin-bottom: 25px;">
      <h2 style="color: #333; margin-top: 0; font-size: 18px;">❌ Mistakes & Missed Opportunities</h2>
      <ul style="color: #555; font-size: 14px; line-height: 1.8;">
        ${analysis.mistakes.map((m: string) => `<li>${m}</li>`).join('')}
      </ul>
    </div>

    <div style="margin-bottom: 25px;">
      <h2 style="color: #333; margin-top: 0; font-size: 18px;">🎯 Missed Opportunities</h2>
      <ul style="color: #555; font-size: 14px; line-height: 1.8;">
        ${analysis.opportunities.map((o: string) => `<li>${o}</li>`).join('')}
      </ul>
    </div>

    <div style="margin-bottom: 25px;">
      <h2 style="color: #333; margin-top: 0; font-size: 18px;">💡 Recommendations for Next Game</h2>
      <ul style="color: #555; font-size: 14px; line-height: 1.8;">
        ${analysis.recommendations.map((r: string) => `<li>${r}</li>`).join('')}
      </ul>
    </div>

    <div style="margin-bottom: 25px; padding: 20px; background-color: #eff6ff; border-left: 4px solid #3b82f6; border-radius: 4px;">
      <h2 style="color: #1e40af; margin-top: 0; font-size: 18px;">📊 Investment Strategy Tips</h2>
      <p style="color: #1e40af; line-height: 1.6; font-size: 14px;">${analysis.investmentTips}</p>
    </div>

    <div style="margin-bottom: 25px;">
      <h3 style="color: #666; font-size: 14px; margin: 0;">Investment Breakdown:</h3>
      <table style="width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px;">
        <tr style="background-color: #f5f5f5;">
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Asset Class</td>
          <td style="padding: 10px; border: 1px solid #ddd; font-weight: bold; text-align: right;">Amount</td>
        </tr>
        ${Object.entries(gameStats.investmentBreakdown)
          .map(
            ([asset, amount]: [string, any]) => `
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd;">${asset}</td>
            <td style="padding: 10px; border: 1px solid #ddd; text-align: right;">₹${amount.toLocaleString('en-IN')}</td>
          </tr>
        `
          )
          .join('')}
      </table>
    </div>

    <div style="text-align: center; color: #999; font-size: 12px; margin-top: 40px; border-top: 1px solid #ddd; padding-top: 20px;">
      <p>Generated by INVESIM - Investment Simulation Game</p>
      <p>${new Date().toLocaleString('en-IN')}</p>
    </div>
  `

  document.body.appendChild(container)

  try {
    // Convert HTML to canvas
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
    })

    // Get canvas dimensions
    const imgWidth = 210 // A4 width in mm
    const pageHeight = 297 // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width
    let heightLeft = imgHeight

    // Create PDF
    const pdf = new jsPDF('p', 'mm', 'a4')
    let position = 0

    // Add pages
    while (heightLeft >= 0) {
      const sourceY = Math.max(0, heightLeft - imgHeight)
      pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, position, imgWidth, imgHeight)
      heightLeft -= pageHeight
      position -= pageHeight

      if (heightLeft > 0) {
        pdf.addPage()
      }
    }

    // Generate blob
    return pdf.output('blob')
  } finally {
    document.body.removeChild(container)
  }
}
